"""abstract_backfill.py — backfill `description:` frontmatter (the L1 abstract).

V7.3.0 (OpenViking-pattern import, ours): the retriever indexes each file's
`description:` frontmatter as a searchable `abstract` column, but the audit
found coverage was ~6/63 brain files and ~0 memory files. This script LLM-
generates a one-line description for every brain/ + memory/ file missing one,
via the local claude CLI (haiku, subscription OAuth — never an API key).

USAGE
-----
    python scripts/core/abstract_backfill.py --dry-run          # show targets + proposed lines
    python scripts/core/abstract_backfill.py                    # write frontmatter
    python scripts/core/abstract_backfill.py --limit 10         # first N only
    python scripts/core/abstract_backfill.py --kinds brain      # restrict scope

SKIPS: files that already have a description, generated docs (the
build_capability_graph --emit-docs header — they get overwritten), and
everything memory_retriever's walker already excludes (STATE, SESSION_LOG, …).
After a run: `python scripts/core/memory_retriever.py build` re-indexes the new
abstracts (file hashes changed).
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "scripts"))

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")
except Exception:  # noqa: BLE001
    pass

from core.memory_retriever import _walk_sources, _extract_description  # noqa: E402

GENERATED_MARKER = "GENERATED by scripts/build_capability_graph.py"
PROMPT = (
    "Write ONE line (max 160 characters) describing this markdown file for a "
    "`description:` frontmatter field. State what the file IS and what an agent "
    "uses it for — concrete, no marketing tone, no quotes, no trailing period "
    "needed. Return ONLY that line.\n\nFILE: {name}\n\nCONTENT (first 60 lines):\n{head}"
)


def _generate(name: str, head: str) -> str | None:
    from lib.model_fallback import run_smart_cli  # noqa: E402
    text = run_smart_cli(PROMPT.format(name=name, head=head), model="haiku", timeout=90,
                         task_type="fast", agent_name="abstract_backfill")
    if not text:
        return None
    line = text.strip().splitlines()[0].strip().strip('"').strip("'")
    return line[:220] if line else None


def _insert_description(text: str, desc: str) -> str:
    safe = desc.replace('"', "'")
    if text.startswith("---\n") or text.startswith("---\r\n"):
        # Insert right after the opening fence so it's first in the block.
        nl = text.index("\n") + 1
        return text[:nl] + f'description: "{safe}"\n' + text[nl:]
    return f'---\ndescription: "{safe}"\n---\n\n' + text


def main() -> int:
    p = argparse.ArgumentParser(description="Backfill description: frontmatter for brain/memory files")
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--limit", type=int, default=0, help="stop after N files (0 = all)")
    p.add_argument("--kinds", default="brain,memory", help="CSV of retriever kinds to cover")
    args = p.parse_args()

    kinds = {k.strip() for k in args.kinds.split(",") if k.strip()}
    targets: list[tuple[str, Path]] = []
    for kind, path in _walk_sources():
        if kind not in kinds:
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        if GENERATED_MARKER in text[:400]:
            continue
        if _extract_description(text):
            continue
        targets.append((kind, path))

    if args.limit:
        targets = targets[: args.limit]
    print(f"[abstract_backfill] {len(targets)} file(s) missing description: in kinds {sorted(kinds)}")

    written = failed = 0
    for kind, path in targets:
        rel = path.relative_to(PROJECT_ROOT).as_posix()
        text = path.read_text(encoding="utf-8", errors="replace")
        head = "\n".join(text.splitlines()[:60])
        desc = _generate(path.name, head)
        if not desc:
            print(f"  FAIL  {rel} (model returned nothing)")
            failed += 1
            continue
        if args.dry_run:
            print(f"  [dry] {rel}\n        -> {desc}")
            continue
        path.write_text(_insert_description(text, desc), encoding="utf-8")
        print(f"  OK    {rel}\n        -> {desc}")
        written += 1

    print(f"[abstract_backfill] wrote {written}, failed {failed}, dry_run={args.dry_run}")
    if written:
        print("Next: python scripts/core/memory_retriever.py build")
    return 0 if not failed else 1


if __name__ == "__main__":
    sys.exit(main())
