"""catalog_sync's --check gate could never exit 0.

Found by the 2026-08-04 automation audit. `_render_block` embeds a fresh
"_Last synced: <iso>_" line on every render, and `_update_file` compared the
whole block — so the rendered text always differed from disk, `--check` always
printed "drift detected", and the gate always exited 1. Running the sync and
re-checking immediately still reported drift.

A permanently-red gate carries no signal: nobody can tell a real count change
from the clock ticking, so the check gets ignored, which is worse than not
having it. Drift means THE COUNTS moved.

Run: python -m pytest scripts/tests/test_catalog_sync_drift.py -q
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCRIPTS = ROOT / "scripts"
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))

import catalog_sync as cs  # noqa: E402


BLOCK = """<!-- MANIFEST:BEGIN -->
_Auto-generated by `scripts/catalog_sync.py` — do not edit this block manually._
_Last synced: {ts}_

| Type | Count |
|---|---:|
| Python scripts | {n} |
<!-- MANIFEST:END -->"""


def _doc(ts: str, n: int) -> str:
    return "# Title\n\nprose\n\n" + BLOCK.format(ts=ts, n=n) + "\n\ntrailing\n"


def test_timestamp_alone_is_not_drift(tmp_path):
    """The actual bug: only the clock moved."""
    f = tmp_path / "CAPABILITIES.md"
    f.write_text(_doc("2026-08-04T10:00:00+00:00", 128), encoding="utf-8")
    newer = BLOCK.format(ts="2026-08-04T23:59:59+00:00", n=128)
    assert cs._update_file(f, newer, check_only=True) == "in sync"


def test_a_real_count_change_is_still_drift(tmp_path):
    """Break-the-test: the gate must still fail when something real moved."""
    f = tmp_path / "CAPABILITIES.md"
    f.write_text(_doc("2026-08-04T10:00:00+00:00", 128), encoding="utf-8")
    changed = BLOCK.format(ts="2026-08-04T23:59:59+00:00", n=131)
    assert cs._update_file(f, changed, check_only=True) == "drift detected"


def test_write_mode_keeps_the_last_synced_field_honest(tmp_path):
    """Codex audit 2026-08-04: the first version skipped the write when only the
    timestamp differed, to avoid git churn. That left "_Last synced_" claiming a
    date that got staler every run while syncs kept succeeding — a field that
    states recency and then lies is worse than churn. --check stays
    timestamp-insensitive; WRITE mode persists."""
    f = tmp_path / "STATE.md"
    f.write_text(_doc("2026-08-04T10:00:00+00:00", 128), encoding="utf-8")
    newer = BLOCK.format(ts="2026-08-05T01:02:03+00:00", n=128)
    assert cs._update_file(f, newer, check_only=False) == "in sync (timestamp refreshed)"
    text = f.read_text(encoding="utf-8")
    assert "2026-08-05T01:02:03+00:00" in text, "last-synced date went stale"
    assert "| Python scripts | 128 |" in text, "counts must be untouched"


def test_check_mode_still_ignores_the_timestamp_after_that_change(tmp_path):
    """The two modes answer different questions and must not drift apart."""
    f = tmp_path / "STATE.md"
    f.write_text(_doc("2026-01-01T00:00:00+00:00", 128), encoding="utf-8")
    newer = BLOCK.format(ts="2026-08-05T01:02:03+00:00", n=128)
    assert cs._update_file(f, newer, check_only=True) == "in sync"


def test_write_mode_persists_a_real_change(tmp_path):
    f = tmp_path / "STATE.md"
    f.write_text(_doc("2026-08-04T10:00:00+00:00", 128), encoding="utf-8")
    changed = BLOCK.format(ts="2026-08-05T01:02:03+00:00", n=131)
    assert cs._update_file(f, changed, check_only=False) == "updated"
    text = f.read_text(encoding="utf-8")
    assert "| Python scripts | 131 |" in text
    assert "2026-08-05T01:02:03+00:00" in text, "timestamp should update on a real sync"


def test_normalizer_only_touches_the_timestamp_line():
    src = "_Last synced: 2026-01-01T00:00:00_\n| Python scripts | 5 |\n"
    out = cs._ignoring_timestamp(src)
    assert "| Python scripts | 5 |" in out
    assert "2026-01-01" not in out
