"""Which markdown files are in the Obsidian vault, and which must never be rewritten.

One module so the vault-hygiene tools cannot drift apart. Two questions live here:

  IS IT IN THE VAULT?  -> `is_ignored(rel, load_ignore_filters())`
    Obsidian indexes a file only if its path escapes every filter in
    `.obsidian/app.json -> userIgnoreFilters`. A tool that ignores those filters
    reports gaps in `.claude/` and `.agents/` — directories Obsidian never sees —
    and makes a clean vault look dirty. RULE 6 forbids editing `.obsidian/`, so
    `ARTIFACT_PREFIXES` extends the exclusions on our side for generated trees.

  IS IT SAFE TO WRITE?  -> `is_protected(rel)`
    Two classes of file look like hand-authored notes and are not:

    GENERATED — rendered from `brain/CAPABILITY_GRAPH.json` by
      `build_capability_graph.py --emit-docs`. Editing one (even to add
      frontmatter) makes it diverge from its generator and
      `scripts/tests/test_generated_docs_fresh.py` fails. Fix = re-emit.

    VENDORED — LOCKSTEP blocks pinned by sha256 in `harness.lock`, shipped by
      the upstream empire-harness package. Any byte change breaks
      `test_harness_canonical.py`, and there is **no local re-sync tool** to
      regenerate the hash. Repo-specific rules belong in the repo-owned
      `seed_core` block in `PERSONAL.md` instead.

Both classes were edited by accident on 2026-07-28 during a vault-wide
frontmatter + orphan-reconnect sweep. That is why this module exists. Import it
in any tool that writes `*.md` in bulk.
"""

from __future__ import annotations

import fnmatch
import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
OBSIDIAN_APP_JSON = REPO_ROOT / ".obsidian" / "app.json"

# Outside the vault regardless of user config.
HARD_IGNORES = frozenset({".git", "node_modules", "__pycache__", ".venv", "venv"})

# Generated / vendored trees that are not knowledge nodes.
ARTIFACT_PREFIXES: tuple[str, ...] = (
    ".pytest_cache/",
    "apps/oasis-desktop/resources/sidecar/",  # regenerated by bundle-sidecar.js
    "evals/",                                  # generated eval fixtures
    "coverage/",
    "dist/",
    "build/",
)

# Rendered by scripts/build_capability_graph.py --emit-docs
GENERATED_DOCS: frozenset[str] = frozenset({
    "brain/WHEN_TO_USE_SKILLS.md",
    "brain/WHEN_TO_USE_AGENTS.md",
    "brain/INDEX.md",
    "memory/INDEX.md",
    "memory/MEMORY_INDEX.md",
})

# Hash-pinned in harness.lock — see the module docstring.
VENDORED_PREFIXES: tuple[str, ...] = (
    "brain/_canonical/",
    ".harness/",
)

# Runtime entry points. Stamped by scripts/genome_sync.py and mirrored
# byte-identically into .gemini/rules/; test_entrypoint_parity.py gates them.
# None of the six carries frontmatter today — adding it to one would break that
# uniformity and desync the mirror until the next genome_sync run.
ENTRY_POINTS: frozenset[str] = frozenset({
    "CLAUDE.md", "GEMINI.md", "ANTIGRAVITY.md",
    "AGENTS.md", "OPENCODE.md", "ZCODE.md",
})


def is_protected(rel_posix: str) -> bool:
    """True if `rel_posix` is generated, vendored, or a genome-managed entry point."""
    return (
        rel_posix in GENERATED_DOCS
        or rel_posix in ENTRY_POINTS
        or rel_posix.startswith(VENDORED_PREFIXES)
    )


def load_ignore_filters() -> list[str]:
    """Read `userIgnoreFilters` from the live Obsidian config."""
    if not OBSIDIAN_APP_JSON.is_file():
        return []
    try:
        cfg = json.loads(OBSIDIAN_APP_JSON.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return []
    return [str(f) for f in (cfg.get("userIgnoreFilters") or []) if isinstance(f, str)]


def is_ignored(rel_posix: str, filters: list[str]) -> bool:
    """Mirror Obsidian's ignore-filter matching (prefix / segment / regex / glob)."""
    parts = rel_posix.split("/")
    if any(p in HARD_IGNORES for p in parts):
        return True
    for raw in filters:
        pat = raw.strip()
        if not pat:
            continue
        if pat.startswith("/") and pat.endswith("/") and len(pat) > 1:
            # Obsidian treats /regex/ filters as regular expressions.
            try:
                if re.search(pat[1:-1], rel_posix):
                    return True
            except re.error:
                pass
            continue
        norm = pat.rstrip("/")
        if rel_posix == norm or rel_posix.startswith(norm + "/"):
            return True
        # A bare token (no slash) matches any path segment, e.g. "node_modules".
        if "/" not in norm and norm in parts:
            return True
        # Trailing-prefix style filters, e.g. "skills/gws-".
        if "/" in norm and rel_posix.startswith(norm):
            return True
        if any(ch in norm for ch in "*?[") and fnmatch.fnmatch(rel_posix, norm):
            return True
    return False


def in_vault(rel_posix: str, filters: list[str] | None = None) -> bool:
    """True if Obsidian indexes this path and it is not a generated artifact."""
    f = load_ignore_filters() if filters is None else filters
    return not is_ignored(rel_posix, f) and not rel_posix.startswith(ARTIFACT_PREFIXES)
