"""One-shot: write today's ranked call sheet as a markdown file."""
import sys
from pathlib import Path
sys.stdout.reconfigure(encoding="utf-8", errors="replace")
sys.path.insert(0, str(Path(__file__).resolve().parent))
from send_gateway import get_supabase
from datetime import datetime, timezone, timedelta

db = get_supabase()
now = datetime.now(timezone.utc)
call_cutoff = (now - timedelta(days=7)).isoformat()

candidates = (db.table("leads")
              .select("id,name,email,phone,company,status,score,notes,last_contacted_at")
              .not_.is_("phone", "null")
              .not_.in_("status", ["lost", "won"])
              .execute().data) or []

recent_called = {r["lead_id"] for r in (db.table("lead_interactions")
                                        .select("lead_id")
                                        .eq("type", "call")
                                        .gte("created_at", call_cutoff)
                                        .execute().data or []) if r.get("lead_id")}

def rank(l):
    status_rank = {"qualified": 0, "contacted": 1, "new": 2}.get(l.get("status") or "new", 3)
    is_named = 1 if (l.get("name") and not l.get("name").startswith("Owner")) else 2
    return (status_rank, is_named, -(l.get("score") or 0))

candidates = [l for l in candidates if l["id"] not in recent_called]
candidates.sort(key=rank)
top10 = candidates[:10]

out = Path(__file__).resolve().parent.parent / "tmp" / "call_sheet_2026-04-20.md"
out.parent.mkdir(exist_ok=True)

lines = [
    "# Cold Call Sheet — 2026-04-20 (3:46 PM)",
    "",
    "## The opener (pattern interrupt)",
    "",
    '> "Hey, is this [name]? — Conaugh from OASIS AI. I know this is cold, can I steal 20 seconds?"',
    "",
    "**[Pause. Wait for them to say sure or no.]**",
    "",
    '> "I work with local service businesses on their booking and follow-up automation — my clients are saving 10+ hours a week on admin. Is that worth a 15-min zoom next week, or am I off base?"',
    "",
    "**If YES** → book Google Meet Tue/Wed/Thu. Use: `python scripts/booking_engine.py auto-book --name \"X\" --email ... --preferred-time \"2026-04-22 14:00\"`",
    "",
    '**If NO** → *"What would need to be true for it to be worth it?"* then either close or move on.',
    "",
    "**If VOICEMAIL** → leave a 20-second message: name, OASIS AI, one specific pain for their business, ask for callback, no number (they have caller ID).",
    "",
    "---",
    "",
    "## The list",
    "",
]

for i, l in enumerate(top10, 1):
    name = l.get("name") or "Owner/Manager"
    company = l.get("company") or ""
    phone = l.get("phone") or ""
    status = l.get("status") or "?"
    last = (l.get("last_contacted_at") or "")[:10] or "never"
    notes = (l.get("notes") or "").strip()
    lead_id = l["id"]

    lines.append(f"### {i}. {name} — {company}")
    lines.append(f"- **Phone:** `{phone}`")
    lines.append(f"- **Status:** `{status}`")
    if last != "never":
        lines.append(f'- **Last email touch:** {last} — you can open with: *"I sent you an email back in March about [company] — not sure if it caught you at a bad time."*')
    if notes:
        lines.append(f"- **Notes:** {notes[:220]}")
    lines.append(f"- **After call, log it:**")
    lines.append(f"  ```bash")
    lines.append(f'  python scripts/lead_engine.py interact {lead_id} --type call --channel phone --content "OUTCOME_HERE"')
    lines.append(f"  ```")
    lines.append("")

lines.append("---")
lines.append("")
lines.append("## Post-call routine (do after each call in <30 sec)")
lines.append("")
lines.append("1. Log the interaction (bash block above — change `OUTCOME_HERE` to one sentence)")
lines.append("2. If they booked → use `booking_engine.py auto-book`")
lines.append("3. If they said NOT interested → mark `lead_engine.py update <id> --status lost --notes \"no fit — reason\"`")
lines.append("4. If VM → `interact ... --type call --content \"left VM\"`")
lines.append("")
lines.append(f"Generated by Bravo at {datetime.now().strftime('%a %b %d, %I:%M %p ET')}")

out.write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote {out}")
print(f"Leads: {len(top10)}")
