"""Catalog sync — regenerate scripts/skills/agents counts from filesystem truth.

Ends the count drift between README, brain/CAPABILITIES.md, brain/STATE.md,
brain/QUICK_REFERENCE.md, and the actual filesystem.

Strategy:
1. Build the manifest via runtime.tool_manifest.build_manifest()
2. Update the fenced <!-- MANIFEST:BEGIN --> ... <!-- MANIFEST:END --> block
   in target docs. If absent, append a fresh block.
3. Never touch prose outside the fenced block.

Usage:
    python scripts/catalog_sync.py              # update all target docs
    python scripts/catalog_sync.py --check      # report drift without writing
    python scripts/catalog_sync.py --json       # emit manifest JSON only
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

# Allow running as script OR as module
REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from runtime.tool_manifest import build_manifest  # noqa: E402

BEGIN = "<!-- MANIFEST:BEGIN -->"
END = "<!-- MANIFEST:END -->"

TARGETS = [
    REPO_ROOT / "brain" / "CAPABILITIES.md",
    REPO_ROOT / "brain" / "STATE.md",
]


def _render_block(m: dict) -> str:
    c = m["counts"]
    lines = [
        BEGIN,
        f"_Auto-generated by `scripts/catalog_sync.py` — do not edit this block manually._",
        f"_Last synced: {m['generated_at']}_",
        "",
        "| Type | Count |",
        "|---|---:|",
        f"| Python scripts | {c['scripts_py']} |",
        f"| PowerShell scripts | {c['scripts_ps1']} |",
        f"| Shell scripts | {c['scripts_sh']} |",
        f"| **Total scripts** | **{c['scripts_total']}** |",
        f"| Skills | {c['skills_total']} ({c['skills_destructive']} destructive) |",
        f"| Agents | {c['agents_total']} |",
        f"| Workflows | {c['workflows_total']} |",
        "",
        "**Scripts by category:**",
        "",
    ]
    for cat, n in sorted(m["counts_by_category"].items(), key=lambda x: -x[1]):
        lines.append(f"- {cat}: {n}")
    lines.extend(["", END])
    return "\n".join(lines)


def _update_file(path: Path, block: str, check_only: bool) -> str:
    if not path.exists():
        return "skipped (missing)"
    text = path.read_text(encoding="utf-8", errors="ignore")
    if BEGIN in text and END in text:
        pattern = re.compile(
            re.escape(BEGIN) + r".*?" + re.escape(END),
            re.DOTALL,
        )
        new_text = pattern.sub(block, text)
        if new_text == text:
            return "in sync"
        if check_only:
            return "drift detected"
        path.write_text(new_text, encoding="utf-8")
        return "updated"
    # Append a new block with spacing
    if check_only:
        return "missing block"
    suffix = "\n\n## Manifest\n\n" + block + "\n"
    path.write_text(text.rstrip() + suffix, encoding="utf-8")
    return "appended"


def _main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(prog="scripts/catalog_sync.py")
    parser.add_argument("--check", action="store_true",
                        help="Report drift without writing")
    parser.add_argument("--json", action="store_true",
                        help="Print manifest JSON and exit")
    parser.add_argument("--target", action="append", default=[],
                        help="Override target files (repeatable)")
    args = parser.parse_args(argv)

    manifest = build_manifest()
    if args.json:
        print(json.dumps(manifest, indent=2))
        return 0

    block = _render_block(manifest)
    targets = [Path(t) for t in args.target] if args.target else TARGETS

    any_drift = False
    for t in targets:
        status = _update_file(t, block, args.check)
        rel = t.relative_to(REPO_ROOT) if t.is_absolute() and t.exists() else t
        print(f"{rel}: {status}")
        if status in {"drift detected", "missing block"}:
            any_drift = True

    if args.check and any_drift:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(_main(sys.argv[1:]))
