#!/usr/bin/env python3
"""Brain freshness checker (audit Phase 9).

Reports brain/*.md files that are STALE (now - last_updated > freshness_threshold_days)
or MISSING a `last_updated` frontmatter date. Memory you can't date is memory you
can't trust. This is a REPORTING tool, not a failing test — wire it into the daily
heartbeat (see PLAYBOOK.md).

Auto-generated docs (brain/INDEX.md, brain/WHEN_TO_USE_SKILLS.md) are skipped —
they're regenerated on demand from the capability graph, so "freshness" is N/A.

Usage:
  python scripts/check_brain_freshness.py            # human report
  python scripts/check_brain_freshness.py --json     # machine output
Exit code: 0 if nothing stale/missing, 1 otherwise (informational; not a test gate).
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import date, datetime
from pathlib import Path

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

ROOT = Path(__file__).resolve().parent.parent
BRAIN = ROOT / "brain"
DEFAULT_THRESHOLD = 30
GENERATED_MARKER = "GENERATED by scripts/build_capability_graph.py"

FM_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)


def _frontmatter(text: str) -> dict[str, str]:
    m = FM_RE.match(text)
    if not m:
        return {}
    fm: dict[str, str] = {}
    for line in m.group(1).splitlines():
        if ":" in line and not line.strip().startswith("#"):
            k, _, v = line.partition(":")
            fm[k.strip()] = v.strip().strip("'\"")
    return fm


def _parse_date(s: str):
    for fmt in ("%Y-%m-%d", "%Y/%m/%d"):
        try:
            return datetime.strptime(s.strip()[:10], fmt).date()
        except (ValueError, TypeError):
            continue
    return None


def scan(today: date | None = None):
    today = today or date.today()
    missing, stale, fresh = [], [], []
    for p in sorted(BRAIN.glob("*.md")):
        text = p.read_text(encoding="utf-8", errors="ignore")
        if GENERATED_MARKER in text:
            continue  # auto-generated; freshness N/A
        fm = _frontmatter(text)
        lu = _parse_date(fm.get("last_updated", "") or fm.get("verified", ""))
        if lu is None:
            missing.append(p.name)
            continue
        try:
            thr = int(str(fm.get("freshness_threshold_days", DEFAULT_THRESHOLD)).split()[0])
        except (ValueError, IndexError):
            thr = DEFAULT_THRESHOLD
        age = (today - lu).days
        (stale if age > thr else fresh).append((p.name, age, thr))
    return missing, stale, fresh


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args()
    missing, stale, fresh = scan()
    if args.json:
        print(json.dumps({
            "missing_frontmatter_date": missing,
            "stale": [{"file": f, "age_days": a, "threshold": t} for f, a, t in stale],
            "fresh_count": len(fresh),
        }, indent=2))
    else:
        print(f"BRAIN FRESHNESS — {len(fresh)} fresh, {len(stale)} stale, {len(missing)} missing-date")
        for f, a, t in stale:
            print(f"  STALE   {f}  ({a}d old > {t}d threshold)")
        for f in missing:
            print(f"  NO-DATE {f}")
        if not stale and not missing:
            print("  All brain docs carry a current last_updated date. [OK]")
    return 0 if not stale and not missing else 1


if __name__ == "__main__":
    sys.exit(main())
