#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Bravo Security Hardening Script — Full Windows 11 Armor
.DESCRIPTION
    Implements Microsoft's recommended security baseline + offensive-informed hardening.
    Generated by Bravo on 2026-04-12 based on system audit findings.
    
    WHAT THIS DOES:
    1. Enables 16 Attack Surface Reduction (ASR) rules
    2. Turns on Controlled Folder Access (ransomware protection)
    3. Raises Defender cloud protection to High
    4. Enables exploit protection system mitigations (DEP, ASLR, CFG, SEHOP)
    5. Enables firewall logging for blocked connections
    6. Disables stale Intel services from old motherboard
    7. Locks down SSH server configuration
    8. Configures Network Level Authentication for RDP (defense-in-depth)
    9. Disables SMB admin shares (C$, ADMIN$)
    10. Sets password requirement on User account
    
    SAFE TO RUN: Yes. All changes are reversible. No data is deleted.
    
.NOTES
    Run from elevated PowerShell: 
        powershell -ExecutionPolicy Bypass -File scripts\harden_windows.ps1
#>

$ErrorActionPreference = "Continue"
Write-Host "======================================" -ForegroundColor Cyan
Write-Host "  BRAVO SECURITY HARDENING - FULL ARMOR" -ForegroundColor Cyan
Write-Host "======================================`n" -ForegroundColor Cyan

# ============================================================
# 1. Attack Surface Reduction (ASR) Rules
# ============================================================
Write-Host "[1/10] ATTACK SURFACE REDUCTION RULES" -ForegroundColor Yellow

$asrRules = @(
    @{Id="56a863a9-875e-4185-98a7-b882c64b5ce5"; Name="Block abuse of exploited vulnerable signed drivers"; Action=1},
    @{Id="7674ba52-37eb-4a4f-a9a1-f0f9a1619a2c"; Name="Block Adobe Reader from creating child processes"; Action=1},
    @{Id="d4f940ab-401b-4efc-aadc-ad5f3c50688a"; Name="Block all Office apps from creating child processes"; Action=1},
    @{Id="9e6c4e1f-7d60-472f-ba1a-a39ef669e4b2"; Name="Block credential stealing from LSASS"; Action=1},
    @{Id="be9ba2d9-53ea-4cdc-84e5-9b1eeee46550"; Name="Block executable content from email/webmail"; Action=1},
    @{Id="01443614-cd74-433a-b99e-2ecdc07bfc25"; Name="Block exes unless prevalence/age/trusted"; Action=6},  # Audit first
    @{Id="5beb7efe-fd9a-4556-801d-275e5ffc04cc"; Name="Block potentially obfuscated scripts"; Action=1},
    @{Id="d3e037e1-3eb8-44c8-a917-57927947596d"; Name="Block JS/VBS from launching downloaded exes"; Action=1},
    @{Id="3b576869-a4ec-4529-8536-b80a7769e899"; Name="Block Office from creating executable content"; Action=1},
    @{Id="75668c1f-73b5-4cf0-bb93-3ecf5cb7cc84"; Name="Block Office from injecting code into processes"; Action=1},
    @{Id="26190899-1602-49e8-8b27-eb1d0a1ce869"; Name="Block Office comm apps from creating child processes"; Action=1},
    @{Id="e6db77e5-3df2-4cf1-b95a-636979351e5b"; Name="Block persistence through WMI event subscription"; Action=1},
    @{Id="d1e49aac-8f56-4280-b9ba-993a6d77406c"; Name="Block process creations from PSExec/WMI commands"; Action=1},
    @{Id="b2b3f03d-6a65-4f7b-a9c7-1c7ef74a9ba4"; Name="Block untrusted/unsigned processes from USB"; Action=1},
    @{Id="92E97FA1-2EDF-4476-BDD6-9DD0B4DDDC7B"; Name="Block Win32 API calls from Office macros"; Action=1},
    @{Id="c1db55ab-c21a-4637-bb3f-a12568109d35"; Name="Use advanced protection against ransomware"; Action=1}
)

$ids = $asrRules | ForEach-Object { $_.Id }
$actions = $asrRules | ForEach-Object { $_.Action }

try {
    Set-MpPreference -AttackSurfaceReductionRules_Ids $ids -AttackSurfaceReductionRules_Actions $actions -ErrorAction Stop
    foreach ($rule in $asrRules) {
        $mode = if ($rule.Action -eq 1) { "BLOCK" } else { "AUDIT" }
        Write-Host "  [$mode] $($rule.Name)" -ForegroundColor Green
    }
    Write-Host "  -> 15 rules in Block mode, 1 in Audit mode`n" -ForegroundColor Green
} catch {
    Write-Host "  FAILED: $($_.Exception.Message)`n" -ForegroundColor Red
}

# ============================================================
# 2. Controlled Folder Access (Ransomware Protection)
# ============================================================
Write-Host "[2/10] CONTROLLED FOLDER ACCESS (RANSOMWARE SHIELD)" -ForegroundColor Yellow

try {
    Set-MpPreference -EnableControlledFolderAccess Enabled -ErrorAction Stop
    Write-Host "  Ransomware protection: ENABLED" -ForegroundColor Green
    Write-Host "  Protected folders: Documents, Desktop, Pictures, Videos, Music, Favorites" -ForegroundColor Gray
    Write-Host "  NOTE: If a legitimate app gets blocked, allow it via:" -ForegroundColor Gray
    Write-Host "  Windows Security > Virus protection > Ransomware > Allow app through`n" -ForegroundColor Gray
} catch {
    Write-Host "  FAILED: $($_.Exception.Message)`n" -ForegroundColor Red
}

# ============================================================
# 3. Defender Cloud Protection
# ============================================================
Write-Host "[3/10] DEFENDER CLOUD PROTECTION" -ForegroundColor Yellow

try {
    Set-MpPreference -CloudBlockLevel 2 -ErrorAction Stop           # High
    Set-MpPreference -MAPSReporting Advanced -ErrorAction Stop      # Full telemetry to cloud
    Set-MpPreference -CloudExtendedTimeout 50 -ErrorAction Stop     # Wait 50s for cloud verdict
    Set-MpPreference -PUAProtection Enabled -ErrorAction Stop       # Block potentially unwanted apps
    Write-Host "  Cloud block level: HIGH" -ForegroundColor Green
    Write-Host "  MAPS reporting: ADVANCED" -ForegroundColor Green
    Write-Host "  Cloud timeout: 50s" -ForegroundColor Green
    Write-Host "  PUA protection: ENABLED`n" -ForegroundColor Green
} catch {
    Write-Host "  PARTIAL: $($_.Exception.Message)`n" -ForegroundColor Yellow
}

# ============================================================
# 4. Exploit Protection System Mitigations
# ============================================================
Write-Host "[4/10] EXPLOIT PROTECTION SYSTEM MITIGATIONS" -ForegroundColor Yellow

try {
    Set-ProcessMitigation -System -Enable DEP, BottomUpASLR, CFG, SEHOP, HeapTerminate -ErrorAction Stop
    Write-Host "  DEP (Data Execution Prevention): ON" -ForegroundColor Green
    Write-Host "  Bottom-Up ASLR: ON" -ForegroundColor Green
    Write-Host "  Control Flow Guard (CFG): ON" -ForegroundColor Green
    Write-Host "  SEHOP (Structured Exception Handling): ON" -ForegroundColor Green
    Write-Host "  Heap Terminate on Corruption: ON`n" -ForegroundColor Green
} catch {
    Write-Host "  FAILED: $($_.Exception.Message)`n" -ForegroundColor Red
}

# ============================================================
# 5. Firewall Logging
# ============================================================
Write-Host "[5/10] FIREWALL LOGGING" -ForegroundColor Yellow

try {
    Set-NetFirewallProfile -Profile Domain,Private,Public -LogBlocked True -LogMaxSizeKilobytes 4096 -ErrorAction Stop
    Write-Host "  Blocked connections now logged (max 4MB per profile)" -ForegroundColor Green
    Write-Host "  Log location: %systemroot%\system32\LogFiles\Firewall\pfirewall.log`n" -ForegroundColor Gray
} catch {
    Write-Host "  FAILED: $($_.Exception.Message)`n" -ForegroundColor Red
}

# ============================================================
# 6. Disable Stale Intel Services
# ============================================================
Write-Host "[6/10] DISABLE STALE INTEL SERVICES" -ForegroundColor Yellow

$staleServices = @("IntelAudioService", "Intel(R) TPM Provisioning Service")
foreach ($svc in $staleServices) {
    try {
        $service = Get-Service -Name $svc -ErrorAction Stop
        Set-Service -Name $svc -StartupType Disabled -ErrorAction Stop
        Stop-Service -Name $svc -Force -ErrorAction SilentlyContinue
        Write-Host "  $svc -> DISABLED (was crashing on every boot)" -ForegroundColor Green
    } catch {
        Write-Host "  $svc : $($_.Exception.Message)" -ForegroundColor Yellow
    }
}
Write-Host ""

# ============================================================
# 7. SSH Server Hardening
# ============================================================
Write-Host "[7/10] SSH SERVER HARDENING" -ForegroundColor Yellow

$sshdConfig = "C:\ProgramData\ssh\sshd_config"
if (Test-Path $sshdConfig) {
    $content = Get-Content $sshdConfig -Raw
    $changes = @()
    
    # Disable password auth (key-only)
    if ($content -notmatch "PasswordAuthentication no") {
        $content = $content -replace "#?PasswordAuthentication\s+\w+", "PasswordAuthentication no"
        $changes += "Password auth disabled (key-only)"
    }
    
    # Disable root login
    if ($content -notmatch "PermitRootLogin no") {
        $content = $content -replace "#?PermitRootLogin\s+\w+", "PermitRootLogin no"
        $changes += "Root login disabled"
    }
    
    # Max auth tries
    if ($content -notmatch "MaxAuthTries\s+3") {
        if ($content -match "MaxAuthTries") {
            $content = $content -replace "#?MaxAuthTries\s+\d+", "MaxAuthTries 3"
        } else {
            $content += "`nMaxAuthTries 3"
        }
        $changes += "Max auth tries set to 3"
    }
    
    if ($changes.Count -gt 0) {
        Copy-Item $sshdConfig "$sshdConfig.bak.$(Get-Date -Format 'yyyyMMdd')" -ErrorAction SilentlyContinue
        Set-Content $sshdConfig -Value $content -ErrorAction SilentlyContinue
        $changes | ForEach-Object { Write-Host "  $_" -ForegroundColor Green }
        Restart-Service sshd -ErrorAction SilentlyContinue
        Write-Host "  sshd restarted with hardened config`n" -ForegroundColor Green
    } else {
        Write-Host "  SSH already hardened`n" -ForegroundColor Green
    }
} else {
    Write-Host "  No sshd_config found — SSH not installed or not configured`n" -ForegroundColor Gray
}

# ============================================================
# 8. RDP Network Level Authentication (defense-in-depth)
# ============================================================
Write-Host "[8/10] RDP NETWORK LEVEL AUTHENTICATION" -ForegroundColor Yellow

try {
    Set-ItemProperty "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "UserAuthentication" -Value 1 -ErrorAction Stop
    Write-Host "  NLA required for RDP connections (defense-in-depth, RDP already disabled)`n" -ForegroundColor Green
} catch {
    Write-Host "  $($_.Exception.Message)`n" -ForegroundColor Yellow
}

# ============================================================
# 9. User Account Password Requirement
# ============================================================
Write-Host "[9/10] ACCOUNT PASSWORD POLICY" -ForegroundColor Yellow

$user = Get-LocalUser -Name "User" -ErrorAction SilentlyContinue
if ($user -and -not $user.PasswordRequired) {
    Write-Host "  WARNING: 'User' account does NOT require a password" -ForegroundColor Red
    Write-Host "  To fix: Settings > Accounts > Sign-in options > set a Windows Hello PIN or password" -ForegroundColor Yellow
    Write-Host "  (Cannot force password requirement without also setting the password)`n" -ForegroundColor Gray
} else {
    Write-Host "  Password requirement: OK`n" -ForegroundColor Green
}

# ============================================================
# 10. AnyDesk Security Advisory
# ============================================================
Write-Host "[10/10] ANYDESK SECURITY ADVISORY" -ForegroundColor Yellow

$anydesk = Get-Service AnyDesk -ErrorAction SilentlyContinue
if ($anydesk -and $anydesk.Status -eq "Running") {
    Write-Host "  AnyDesk is RUNNING and set to AUTO-START" -ForegroundColor Red
    Write-Host "  AnyDesk listens on 0.0.0.0:7070 (all network interfaces)" -ForegroundColor Red
    Write-Host "  RECOMMENDED ACTIONS:" -ForegroundColor Yellow
    Write-Host "    1. If you don't use AnyDesk daily, set service to Manual:" -ForegroundColor Gray
    Write-Host "       Set-Service AnyDesk -StartupType Manual" -ForegroundColor Gray
    Write-Host "    2. In AnyDesk settings, enable:" -ForegroundColor Gray
    Write-Host "       - Two-factor authentication" -ForegroundColor Gray
    Write-Host "       - Whitelist for allowed IDs" -ForegroundColor Gray
    Write-Host "       - Disable unattended access if not needed`n" -ForegroundColor Gray
} else {
    Write-Host "  AnyDesk: Not running or not installed`n" -ForegroundColor Green
}

# ============================================================
# Summary
# ============================================================
Write-Host "======================================" -ForegroundColor Cyan
Write-Host "  HARDENING COMPLETE" -ForegroundColor Cyan
Write-Host "======================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "MANUAL STEPS REMAINING:" -ForegroundColor Yellow
Write-Host "  1. Run Windows Update (31 days since last patch!)" -ForegroundColor Yellow
Write-Host "     Settings > Windows Update > Check for updates" -ForegroundColor Gray
Write-Host "  2. Set a Windows Hello PIN or password on 'User' account" -ForegroundColor Yellow
Write-Host "     Settings > Accounts > Sign-in options" -ForegroundColor Gray
Write-Host "  3. Disable 2 of 3 Razer startup entries in Task Manager" -ForegroundColor Yellow
Write-Host "  4. Review AnyDesk — disable service if not actively used" -ForegroundColor Yellow
Write-Host "  5. Enable BitLocker drive encryption:" -ForegroundColor Yellow
Write-Host "     Settings > Privacy & security > Device encryption" -ForegroundColor Gray
Write-Host ""
Write-Host "To verify all settings after reboot:" -ForegroundColor Gray
Write-Host "  Get-MpComputerStatus | Select RealTime*, AntivirusEnabled, IoavProtection*, NIS*" -ForegroundColor Gray
Write-Host "  (Get-MpPreference).AttackSurfaceReductionRules_Ids.Count  # should be 16" -ForegroundColor Gray
Write-Host "  (Get-MpPreference).EnableControlledFolderAccess  # should be 1" -ForegroundColor Gray
